apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 99-sysctl-nr-hugepages
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
      - contents:
          # vm.nr_hugepages=256
          source: data:text/plain;charset=utf-8;base64,dm0ubnJfaHVnZXBhZ2VzPTI1Ngo=
        filesystem: root
        mode: 0644
        path: /etc/sysctl.d/99-nr-hugepages.conf