FROM maven:latest as builder

USER 0
RUN mkdir -p /src/ && cd /src/ \
    && git clone https://github.com/microservices-demo/queue-master

# Decided to split the steps here to avoid rebuilding/cloning needlessly.

RUN cd src/queue-master && mvn clean package -DskipTests && find . -iname '*.jar'

USER 1001

FROM registry.access.redhat.com/ubi8/openjdk-11:1.15-1.1682059493

ENV	SERVICE_USER=myuser \
	SERVICE_UID=10001 \
	SERVICE_GROUP=mygroup \
	SERVICE_GID=10001

USER 0
RUN microdnf update -y \
    && microdnf install -y nc tzdata openssl curl ca-certificates fontconfig glibc-langpack-en gzip tar findutils shadow-utils \
    && groupadd -r -g ${SERVICE_GID} ${SERVICE_GROUP} \
    && useradd -r -u ${SERVICE_UID} -g ${SERVICE_GROUP} -m -d /home/${SERVICE_USER} -s /sbin/nologin ${SERVICE_USER}
    && setcap 'cap_net_bind_service=+ep' $(readlink -f $(which java))

WORKDIR /
EXPOSE 8080

COPY --from=builder /src/queue-master/target/*.jar ./app.jar
RUN	chown -R ${SERVICE_USER}:${SERVICE_GROUP} ./app.jar

USER ${SERVICE_USER}

ENTRYPOINT ["java","-Djava.security.egd=file:/dev/urandom", "-jar","./app.jar", "--port=8080"]