FROM registry.access.redhat.com/ubi9/openjdk-11:latest as builder

USER 0
RUN mkdir -p /src/ && cd /src/ \
    && microdnf install -y git \
    && git clone https://github.com/microservices-demo/orders

# Decided to split the steps here to avoid rebuilding/cloning needlessly.

RUN cd /src/orders && mvn clean package -DskipTests && find . -iname '*.jar'

USER 1001

FROM registry.access.redhat.com/ubi9/openjdk-11:latest

ENV	SERVICE_USER=myuser \
	SERVICE_UID=10001 \
	SERVICE_GROUP=mygroup \
	SERVICE_GID=10001

USER 0
RUN microdnf update -y \
    && microdnf install -y nc tzdata openssl curl ca-certificates fontconfig glibc-langpack-en gzip tar findutils shadow-utils \
    && groupadd -r -g ${SERVICE_GID} ${SERVICE_GROUP} \
    && useradd -r -u ${SERVICE_UID} -g ${SERVICE_GROUP} -m -d /home/${SERVICE_USER} -s /sbin/nologin ${SERVICE_USER}

WORKDIR /
EXPOSE 8080

COPY --from=builder /src/orders/target/*.jar ./app.jar
RUN	chown -R ${SERVICE_USER}:${SERVICE_GROUP} ./app.jar

USER ${SERVICE_USER}

ENTRYPOINT ["/usr/local/bin/java.sh","-jar","./app.jar", "--port=8080"]