FROM registry.access.redhat.com/ubi8/go-toolset:1.18.10-1.1682304657 as builder
ENV sourcesdir /go/src/github.com/microservices-demo/catalogue/

USER 0
RUN mkdir -p /go/src/github.com/microservices-demo/ \
    && cd /go/src/github.com/microservices-demo/ \
    && git clone https://github.com/microservices-demo/catalogue.git

# Decided to split the steps here to avoid rebuilding/cloning needlessly.

RUN go install github.com/FiloSottile/gvt@latest \
    && find / -iname gvt -type f \
    && cd /go/src/github.com/microservices-demo/catalogue && /opt/app-root/src/go/bin/gvt restore \
    && go mod init github.com/microservices-demo/catalogue \
    && go mod tidy \
    && CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o /app github.com/microservices-demo/catalogue/cmd/cataloguesvc \
    && find / -name user -type f
USER 1001

FROM registry.access.redhat.com/ubi8/ubi-minimal:8.7-1107

ENV	SERVICE_USER=myuser \
	SERVICE_UID=10001 \
	SERVICE_GROUP=mygroup \
	SERVICE_GID=10001

RUN microdnf update -y \
    && microdnf install -y nc tzdata openssl curl ca-certificates fontconfig glibc-langpack-en gzip tar findutils shadow-utils \
    && groupadd -r -g ${SERVICE_GID} ${SERVICE_GROUP} \
    && useradd -r -u ${SERVICE_UID} -g ${SERVICE_GROUP} -m -d /home/${SERVICE_USER} -s /sbin/nologin ${SERVICE_USER}

ENV HATEAOS user
ENV USER_DATABASE mongodb
ENV MONGO_HOST user-db

WORKDIR /
EXPOSE 8080

COPY --from=builder /app /app
COPY --from=builder /go/src/github.com/microservices-demo/catalogue/images/ /images/

RUN	chmod +x /app && \
	chown -R ${SERVICE_USER}:${SERVICE_GROUP} /app /images

USER ${SERVICE_USER}

CMD ["/app", "-port=8080"]