FROM registry.access.redhat.com/ubi9/go-toolset:latest as builder
ENV sourcesdir /go/src/github.com/microservices-demo/user/
ENV MONGO_HOST mytestdb:27017
ENV HATEAOS user
ENV USER_DATABASE mongodb

USER 0
RUN mkdir -p /go/src/github.com/microservices-demo/ \
    && cd /go/src/github.com/microservices-demo/ \
    && git clone https://github.com/microservices-demo/user.git

FROM docker.io/library/mongo:3
RUN mkdir -p /scripts/
COPY --from=builder /go/src/github.com/microservices-demo/user/docker/user-db/scripts /docker-entrypoint-initdb.d/

COPY files/user-db-init.sh /docker-entrypoint-initdb.d/
# Modify child mongo to use /data/db-accounts as dbpath (because /data/db wont persist the build because it is already a VOLUME)
RUN mkdir -p /data/db-users \
    && echo "dbpath = /data/db-users" > /etc/mongodb.conf \
    && chown -R mongodb:mongodb /data/db-users \
    && mkdir -p /logs \
    && chown -R mongodb:mongodb /logs \
    && rm -f /docker-entrypoint-initdb.d/mongo_create_insert.sh

USER mongodb
#RUN mongod --fork --logpath /logs/mongodb.log --dbpath /data/db-users  \
#    && /scripts/mongo_create_insert.sh \
#    && mongod --dbpath /data/db-users --shutdown \
#    && chown -R mongodb /data/db-users

# Make the new dir a VOLUME to persist it
VOLUME /data/db-users

CMD ["mongod", "--config", "/etc/mongodb.conf", "--smallfiles"]
