FROM weaveworksdemos/user:0.4.7 as builder

FROM registry.access.redhat.com/ubi8/ubi-minimal:8.7-1107

ENV     SERVICE_USER=myuser \
        SERVICE_UID=10001 \
        SERVICE_GROUP=mygroup \
        SERVICE_GID=10001

RUN microdnf update -y \
    && microdnf install -y nc tzdata openssl curl ca-certificates fontconfig glibc-langpack-en gzip tar findutils shadow-utils \
    && groupadd -r -g ${SERVICE_GID} ${SERVICE_GROUP} \
    && useradd -r -u ${SERVICE_UID} -g ${SERVICE_GROUP} -m -d /home/${SERVICE_USER} -s /sbin/nologin ${SERVICE_USER} \
    && mkdir -p /opt

WORKDIR /opt
EXPOSE 8080
COPY --from=builder /user /opt/

RUN     chmod +x /opt/user && \
        chown -R ${SERVICE_USER}:${SERVICE_GROUP} /opt/user

USER ${SERVICE_USER}

CMD ["/opt/user", "-port=8080"]

