FROM registry.access.redhat.com/ubi8/go-toolset:1.18.10-1.1682304657 as builder
ENV sourcesdir /go/src/github.com/microservices-demo/user/
ENV MONGO_HOST mytestdb:27017
ENV HATEAOS user
ENV USER_DATABASE mongodb

USER 0
RUN mkdir -p /go/src/github.com/microservices-demo/ \
    && cd /go/src/github.com/microservices-demo/ \
    && git clone https://github.com/microservices-demo/user.git

# Decided to split the steps here to avoid rebuilding/cloning needlessly.

RUN cd /go/src/github.com/microservices-demo/user && go mod init github.com/microservices-demo/user \
    && go mod tidy && GOOS=linux go build . && find / -name user -type f
USER 1001

FROM registry.access.redhat.com/ubi8/ubi-minimal:8.7-1107

ENV	SERVICE_USER=myuser \
	SERVICE_UID=10001 \
	SERVICE_GROUP=mygroup \
	SERVICE_GID=10001

RUN microdnf update -y \
    && microdnf install -y nc tzdata openssl curl ca-certificates fontconfig glibc-langpack-en gzip tar findutils shadow-utils \
    && groupadd -r -g ${SERVICE_GID} ${SERVICE_GROUP} \
    && useradd -r -u ${SERVICE_UID} -g ${SERVICE_GROUP} -m -d /home/${SERVICE_USER} -s /sbin/nologin ${SERVICE_USER}

ENV HATEAOS user
ENV USER_DATABASE mongodb
ENV MONGO_HOST user-db

WORKDIR /
EXPOSE 8080
COPY --from=builder /go/src/github.com/microservices-demo/user/user /

RUN	chmod +x /user && \
	chown -R ${SERVICE_USER}:${SERVICE_GROUP} /user

USER ${SERVICE_USER}

CMD ["/user", "-port=8080"]